---
# EDA Rulebook for Terraform Infrastructure Events
# This rulebook listens to the terraform-infrastructure-events stream
# and triggers AAP job templates when infrastructure is provisioned

- name: Terraform Infrastructure Event Handler
  hosts: all
  
#  sources:
#    - name: Listen to Terraform event stream
#      ansible.eda.generic:
#        event_stream_name: terraform-infrastructure-events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.insert_hosts_to_meta:
            host_path: payload.limit
        
  rules:
    # Main rule: Handle Terraform Actions job template trigger
    - name: Handle Terraform Action Job Template
      condition: >
        event.payload.template_type == "job" and
        event.payload.job_template_name == "Configure AWS Infrastructure"
      
      action:
        run_job_template:
          name: "{{ event.payload.job_template_name }}"
          organization: "{{ event.payload.organization_name }}"
    
    # Secondary rule: Log all Terraform events for debugging
    - name: Log Terraform Events
      condition: event.source == "terraform"
      action:
        debug:
          msg: |
            Received Terraform event:
            - Type: {{ event.event_type }}
            - Workspace: {{ event.terraform.workspace }}
            - Run ID: {{ event.terraform.run_id }}
            - Timestamp: {{ event.timestamp }}
    
    # Error handling: Log unexpected events
    - name: Log Unknown Events
      condition: event.source != "terraform"
      action:
        debug:
          msg: "Received unexpected event from source: {{ event.source }}"

# Made with Bob
